[2025-05-21T13:42:55.279+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T13:42:55.299+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_concat_upload_to_gcs.run_etl manual__2025-05-21T13:42:52.127877+00:00 [queued]>
[2025-05-21T13:42:55.306+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_concat_upload_to_gcs.run_etl manual__2025-05-21T13:42:52.127877+00:00 [queued]>
[2025-05-21T13:42:55.306+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 2
[2025-05-21T13:42:55.337+0000] {taskinstance.py:2907} INFO - Executing <Task(PythonOperator): run_etl> on 2025-05-21 13:42:52.127877+00:00
[2025-05-21T13:42:55.344+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-21T13:42:55.346+0000] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2025-05-21T13:42:55.345+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_concat_upload_to_gcs', 'run_etl', 'manual__2025-05-21T13:42:52.127877+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_taxi_data_extractor.py', '--cfg-path', '/tmp/tmp2p2305za']
[2025-05-21T13:42:55.348+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask run_etl
[2025-05-21T13:42:55.442+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_concat_upload_to_gcs.run_etl manual__2025-05-21T13:42:52.127877+00:00 [running]> on host 939a293d2c0e
[2025-05-21T13:42:55.640+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_concat_upload_to_gcs' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T13:42:52.127877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T13:42:52.127877+00:00'
[2025-05-21T13:42:55.641+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-21T13:42:55.740+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/taxi_data_extractor.py", line 105, in main
    local_output_path = concater.Concancenate()
                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Concater' object has no attribute 'Concancenate'. Did you mean: 'concancenate'?
[2025-05-21T13:42:55.897+0000] {taskinstance.py:1242} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_concat_upload_to_gcs, task_id=run_etl, run_id=manual__2025-05-21T13:42:52.127877+00:00, execution_date=20250521T134252, start_date=20250521T134255, end_date=20250521T134255
[2025-05-21T13:42:56.147+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-21T13:42:56.147+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task run_etl ('Concater' object has no attribute 'Concancenate'; 81)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/taxi_data_extractor.py", line 105, in main
    local_output_path = concater.Concancenate()
                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Concater' object has no attribute 'Concancenate'. Did you mean: 'concancenate'?
[2025-05-21T13:42:56.162+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-21T13:42:56.177+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T13:42:56.219+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
